# Generated by Django 5.0.3 on 2024-04-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.IntegerField(null=True, verbose_name='valor por unidad'),
        ),
        migrations.AddField(
            model_name='task',
            name='stock',
            field=models.IntegerField(null=True, verbose_name='cantidad de stock'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=65, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('v', 'Verduras de hoja verde'), ('r', 'Raices'), ('t', 'Tuberculos'), ('d', 'Verduras de temporada')], max_length=1, verbose_name='Categoria'),
        ),
    ]
