# Generated by Django 5.0.3 on 2024-04-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Facturation',
        ),
        migrations.AddField(
            model_name='task',
            name='actives',
            field=models.CharField(choices=[('d', 'Disponible'), ('n', 'No Disponible')], max_length=1, null=True, verbose_name='Categoria'),
        ),
    ]
