# Generated by Django 5.0.3 on 2024-04-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_cartitem_facturation_task_actives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='stock',
        ),
    ]
